### ISSUE TITLE
get also non keyframes with seekEncodedAudioChunk

### ISSUE THREAD

**Issue by Pensarfeo** [ForeverSc/web-demuxer#10]
Hi

How can I get non keyframes with seekEncodedAudioChunk? from the documentation I see getting keyframes but I don't understand how can I get the rest :)

Thank you!

**Comment by ForeverSc** [comment]
Upgrade to version 2.2.0 and use `seekEncodedAudioChunk(time, AVSeekFlag.AVSEEK_FLAG_ANY)`. `AVSeekFlag.AVSEEK_FLAG_ANY` allows seeking to any frame, including non-keyframes.

**Comment by Pensarfeo** [comment]
Thanks!
