### ISSUE TITLE
Makefile questions

### ISSUE THREAD

**Issue by daniellovera** [ForeverSc/web-demuxer#14]
Hi,

Thanks for sharing this, it's excellent. I have a couple questions though.

Is this https://github.com/ForeverSc/web-demuxer/blob/6a59c214390819af35c16b6598ac62297eb91c5d/Makefile#L17 supposed to be `mpegts` instead of `mpegi`? I don't think FFmpeg accepts mpegi as a demuxer config, and I presume you were targetting the MPEG-2 container, which is extension .m2ts?

Why does the full size wasm have decoders enabled
https://github.com/ForeverSc/web-demuxer/blob/6a59c214390819af35c16b6598ac62297eb91c5d/Makefile#L16
but the mini does not?

Thanks again!

**Comment by ForeverSc** [comment]
You are right! Thanks for finding the mistake. `mpegi` was a typo; I actually meant to write `mpeg`. 
Regarding enabling decoders, for some formats such as FLV, if you only enable the demuxer without the decoders, you won’t be able to get certain information like width and height. I think it may not store some information in the container, so we need to use decoders. However, I haven’t fully investigated the exact reason yet, and there may be other good solutions.
