### ISSUE TITLE
WebM 视频格式，透明通道丢失

### ISSUE THREAD

**Issue by juntaosun** [ForeverSc/web-demuxer#16]
我测试了 WebM 透明视频，其中包含BGRA通道，但解码后获得的像素只有BGR通道。透明A通道像素丢失了。

```
yuv420p   

yuva420p（支持A通道透明）
```

使用这样的ffmpeg命令：（将PNG文件生成 YUVA 透明视频）
```
ffmpeg -i image%04d.png output.webm
```

Chrome 视频的 Alpha 透明度：
https://developer.chrome.com/blog/alpha-transparency-in-chrome-video?hl=zh-cn

如何确认 webm 视频带有透明通道，将它拖到 Chrome 浏览器中，可以预览。

**Comment by ForeverSc** [comment]
目前WebCodecs不支持Alpha通道: https://github.com/w3c/webcodecs/issues/377 ，demuxer无法解决，只能等WebCodecs的后续支持了
