### ISSUE TITLE
Question: Subtitles

### ISSUE THREAD

**Issue by daniellovera** [ForeverSc/web-demuxer#19]
Hi,

I'm curious if you've given thought into supporting demuxing subtitles (or other non-video/audio streams). My use case is that I want to use web-demuxer to demux video/audio so I can decode/encode with Webcodecs API. However, when it's time to remux the re-encoded streams I'd prefer not to have to spin up another demuxer to grab the subtitles.

I may be missing something completely obvious here though, but appreciate your consideration in advance.

Thanks!
Daniel

**Comment by ForeverSc** [comment]
reading subtitles isn’t provided as a dedicated method, but you can use `readAVPacket(0, 0, AVMediaType.AVMEDIA_TYPE_SUBTITLE)` to retrieve subtitle data, as well as data from other streams.

**Comment by daniellovera** [comment]
Thanks. I read the "AV" part of that method and assumed it would only work for Audio and Video. Appreciate the response.
