### ISSUE TITLE
Memory Management Description

### ISSUE THREAD

**Issue by pins3l** [ForeverSc/web-demuxer#4]
Great work first of all, the library is very impressive!

Though I have a question about memory management. Is this library holding the entire arraybuffer of a file in memory or will the file be read and demuxed progressively. E.g. if I would like to demux a 2GB 4k video will the entire 2GB allocated in memory?

**Comment by ForeverSc** [comment]
Thanks! It will not load the whole file into memory. You can try the [video play example](https://foreversc.github.io/web-demuxer/#example-play). I use `readAVPacket` to read one packet and render one frame in the canvas. Then the packet memory will be automatically recovered by the browser when you call `frame.close()`. For details, you can see the [example code](https://github.com/ForeverSc/web-demuxer/blob/main/index.html#L143-L183).
