### ISSUE TITLE
Is there a way to seek videos by frame number

### ISSUE THREAD

**Issue by Pensarfeo** [ForeverSc/web-demuxer#5]
Hi
Is there a way to seek the videos by frame number?
I can't just convert a frame number to a given time as for my application I am working with videos that most likely will not have frames at regular intervals. 

Thanks for this awesome package!
Grate work!

**Comment by ForeverSc** [comment]
The variable frame rate added complexity to the problem. I couldn’t find a good solution using FFmpeg. I considered a solution that involves using `readVideoPacket` to obtain the PTS timestamp of each frame and building a map of frame count to timestamp. Then, I would use `seekEncodedVideoChunk`.

**Comment by Pensarfeo** [comment]
Hi, Thanks, this is kind of what I am doing now!

Cheers
Pedro
