### ISSUE TITLE
Failing to play avi files

### ISSUE THREAD

**Issue by Pensarfeo** [ForeverSc/web-demuxer#6]
Hi, It seems like .avi files fail to play cause the codec value is 'undf', which I think it means undefined :)
Any idea on how to fix it?

Thanks for your help!

**Comment by ForeverSc** [comment]
If the codec value is `undf`, it means that the codec is not supported by [WebCodecs](https://w3c.github.io/webcodecs/codec_registry.html#video-codec-registry). Even if we obtain the correct frame packet, it cannot be decoded by the browser, so `web-demuxer` does not support it.

**Comment by Pensarfeo** [comment]
Got it, thanks!

**Comment by hellozyemlya** [comment]
@ForeverSc but is it possible to build ffmpeg with software codecs and use them to decode frames of other codecs, from the list that webcodecs not supports?

**Comment by ForeverSc** [comment]
> @ForeverSc but is it possible to build ffmpeg with software codecs and use them to decode frames of other codecs, from the list that webcodecs not supports?

Of course you can. But web-demuxer is designed for demuxing, so it will not support decoding. However, you can fork it and add decoding by yourself.
