### ISSUE TITLE
Playing an Audio Track

### ISSUE THREAD

**Issue by juntaosun** [ForeverSc/web-demuxer#7]
Very nice project.
Could you update the "Play Video" example to include an example that plays the video sound (audio track)?
That would be great~

---

非常好的项目。
您可以在“Play Video”示例中，更新增加一个同步播放视频声音（音频轨道）的示例吗？
这样就太好了~

**Comment by ForeverSc** [comment]
可以先参考下[WebCodecs同时播放音视频的样例](https://github.com/w3c/webcodecs/tree/main/samples/audio-video-player)，把mp4box.js换成web-demuxer就可以了。后续有空我再加下或者也欢迎提个PR

**Comment by ForeverSc** [comment]
因为readAVPacket会占用worker，导致另外一个无法执行。可以再创建一个demuxer，专门给音频用，这样就会新建一个worker，互相不影响。

**Comment by ForeverSc** [comment]
后续我再补充个同时读取的方法

**Comment by ForeverSc** [comment]
> 因为readAVPacket会占用worker，导致另外一个无法执行。可以再创建一个demuxer，专门给音频用，这样就会新建一个worker，互相不影响。

@juntaosun 有试过这个方法么？想了下同时读取会让API有些意义模糊不清，还是分开处理会好些
