### ISSUE TITLE
Can't load file from worker in Mac OS (safari)

### ISSUE THREAD

**Issue by Pensarfeo** [ForeverSc/web-demuxer#8]
Hi, I keep getting the following error: "Not allowed to load local resource: blob:null/bafac9b4-e0e6-42b6-81ed-142f18a5147f"

When trying to get the avpacket reader. I do not see this issue in chrome on Mac or windows and it only happens when I run from worker. This is the function I use to create the reader:

```js
async function createReader(arrayBuffer) {
  const blob = new Blob([arrayBuffer], {type: 'video/mov'})
  const blobURL = URL.createObjectURL(blob);
  const toParseFile = new File([blob], `${i}.file`)
  await webDemuxer.load(toParseFile)
 
  const reader = webDemuxer.readAVPacket().getReader()
  return reader
}
```

I tried to debug the issue and the error seems to happen to the point in which the file is posted to the wasmworker

**Comment by ForeverSc** [comment]
This problem may be caused by Safari. I think it might not support posting a File between workers. Did you test posting a File to another worker(not wasm worker)?

**Comment by Pensarfeo** [comment]
No, I ended up moving the functionality out of workers for safari.
I had the same hunch to!

Thanks for the feedback!

**Comment by lvscar** [comment]
> This problem may be caused by Safari. I think it might not support posting a File between workers. Did you test posting a File to another worker(not wasm worker)?

Posting files, Blobs, or ArrayBuffers  to a web worker works fine for my case. The issue was that Safari cannot load binary data in a web worker. The problem was resolved after I moved the demuxing data loading to the main thread for Safari.
